<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>Relativity.Server.Transfer.SDK.Samples</RootNamespace>
    <AssemblyName>Relativity.Server.Transfer.SDK.Samples</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="Polly" Version="5.3.1" />
    <PackageReference Include="Relativity.Server.DataTransfer.SDK" Version="26000.0.9" />
    <PackageReference Include="Relativity.Server.Kepler.Client.SDK" Version="5001.0.7" />
    <PackageReference Include="Relativity.Server.Kepler.SDK" Version="5001.0.7" />
    <PackageReference Include="Relativity.Server.Logging.Interfaces.SDK" Version="5005.0.1" />
    <PackageReference Include="Relativity.Server.Logging.SDK" Version="5005.0.1" />
    <PackageReference Include="Relativity.Server.Services.DataContracts.SDK" Version="5002.1.0" />
    <PackageReference Include="Relativity.Server.Services.Interfaces.SDK" Version="5002.1.0" />
    <PackageReference Include="Relativity.Server.Transfer.SDK" Version="26000.0.8" />
    <PackageReference Include="System.Reactive" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LogConfig.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\EDRM-Sample1.JPG">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\EDRM-Sample2.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\EDRM-Sample3.doc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\EDRM-Sample4.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\EDRM-Sample5.pptx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
